# Generated by Django 4.2.5 on 2023-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Courses', models.CharField(max_length=200)),
            ],
        ),
    ]
