# Generated by Django 4.2.5 on 2023-09-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_database',
            name='Courses',
            field=models.CharField(max_length=199),
        ),
    ]
