# Generated by Django 5.0.1 on 2024-01-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuserproxy',
            options={'verbose_name': 'Staff User', 'verbose_name_plural': 'Staff Users'},
        ),
        migrations.AlterModelOptions(
            name='superadminuserproxy',
            options={'verbose_name': 'Super Admin', 'verbose_name_plural': 'Super Admins'},
        ),
    ]
