# Generated by Django 5.0.3 on 2024-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasenoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
