# Generated by Django 4.2.5 on 2023-11-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_data_for_recommender',
        ),
    ]
