# Generated by Django 5.0.3 on 2024-06-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
