# Generated by Django 5.0.3 on 2024-06-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='Aggregate_points',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='CAT_1_marks',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='CAT_2_marks',
            field=models.FloatField(default=18),
        ),
    ]
