# Generated by Django 4.2.5 on 2023-11-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0002_delete_course_data_for_recommender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender_training_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100)),
                ('Course_objectives', models.CharField(max_length=100)),
                ('Course_general_info_and_about', models.CharField(max_length=100)),
                ('General_prereuisites', models.CharField(max_length=100)),
                ('Subject_prerequisites', models.CharField(max_length=100)),
            ],
        ),
    ]
