# Generated by Django 5.0.3 on 2024-06-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0002_remove_probabilitydatatable_activity_in_group_discussions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeinformation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_app.studentuser'),
        ),
    ]
