# Generated by Django 5.0.3 on 2024-06-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0002_alter_studentuser_aggregate_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='Lessons_Attended',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='activity_on_elearning_platforms',
            field=models.FloatField(default=74),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='activity_on_learning_platforms',
            field=models.FloatField(default=75),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='homework_submission_rates',
            field=models.FloatField(default=74),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='pcnt_of_lessons_attended',
            field=models.FloatField(default=47),
        ),
    ]
