# Generated by Django 4.2.5 on 2024-06-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0002_baseuser_role'),
        ('academia_app', '0002_studentuser_aggregate_points_studentuser_cat_1_marks_and_more'),
    ]

    operations = [
    ]
