# Generated by Django 4.2.6 on 2023-10-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0003_fieldofinterest_highschoolsubject_courseofinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='school',
            name='departments_count',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
