# Generated by Django 4.2.5 on 2023-10-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0003_fieldofinterest_highschoolsubject_courseofinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_data_for_recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=255)),
                ('Course_Objectives', models.TextField()),
                ('Course_General_Info_and_About', models.TextField()),
                ('Prerequisites', models.TextField()),
            ],
        ),
    ]
