# Generated by Django 4.2.5 on 2024-01-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0002_alter_adminuserproxy_options_and_more'),
        # ('academia_app', '0003_fieldofinterest_highschoolsubject_courseofinterest'),
    ]

    operations = [
    ]
