# Generated by Django 4.2.6 on 2023-10-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0004_remove_course_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program_code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
