# Generated by Django 4.2.5 on 2024-01-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0004_merge_20240110_1800'),
        ('academia_app', '0004_userprofile_full_name_and_more'),
    ]

    operations = [
    ]
