# Generated by Django 5.0.3 on 2024-03-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0003_message'),
        ('academia_app', '0005_unit_delete_customuser'),
    ]

    operations = [
    ]
