# Generated by Django 4.2.5 on 2024-01-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0005_merge_20240117_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender_training_data_tokenized_sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_objectives', models.CharField(max_length=100)),
                ('course_general_info_and_about', models.CharField(max_length=100)),
                ('general_prerequisites', models.CharField(max_length=100)),
                ('subject_prerequisites', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recommender_training_data_vectorized_sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_objectives', models.CharField(max_length=100)),
                ('course_general_info_and_about', models.CharField(max_length=100)),
                ('general_prerequisites', models.CharField(max_length=100)),
                ('subject_prerequisites', models.CharField(max_length=100)),
            ],
        ),
    ]
