# Generated by Django 4.2.6 on 2023-10-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0005_course_program_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prefix',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
