# Generated by Django 4.2.5 on 2024-01-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0006_recommender_training_data_tokenized_sentences_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommender_training_data_vectorized_sentences',
            new_name='Recommender_training_data_sentence_vectors',
        ),
    ]
