# Generated by Django 4.2.6 on 2023-10-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0007_alter_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_code',
            field=models.CharField(default=None, max_length=15, null=True, unique=True),
        ),
    ]
