# Generated by Django 4.2.5 on 2024-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0008_rename_recommender_training_data_sentence_vectors_recommender_training_data_vectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender_training_data_number_vectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_objectives', models.CharField(max_length=100)),
                ('course_general_info_and_about', models.CharField(max_length=100)),
                ('general_prerequisites', models.CharField(max_length=100)),
                ('subject_prerequisites', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Recommender_training_data_vectors',
            new_name='Recommender_training_data_byte_vectors',
        ),
    ]
