# Generated by Django 4.2.6 on 2023-10-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0008_alter_course_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prefix',
            field=models.CharField(default=None, max_length=15, null=True, unique=True),
        ),
    ]
