# Generated by Django 4.2.5 on 2024-01-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0003_remove_course_graduation_probability_and_more'),
        ('academia_app', '0009_recommender_training_data_number_vectors_and_more'),
    ]

    operations = [
    ]
