# Generated by Django 4.2.5 on 2024-01-28 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0010_merge_20240126_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='graduation_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='course_general_info_and_about',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='course_objectives',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='general_prerequisites',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='subject_prerequisites',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
