# Generated by Django 4.2.6 on 2023-12-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0004_course_data_for_recommender'),
        ('academia_app', '0010_alter_course_name'),
    ]

    operations = [
    ]
