# Generated by Django 4.2.5 on 2024-01-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0011_course_graduation_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='course_general_info_and_about',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='course_objectives',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='general_prerequisites',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='subject_prerequisites',
            field=models.BinaryField(),
        ),
    ]
