# Generated by Django 4.2.5 on 2024-01-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0012_alter_recommender_training_data_number_vectors_course_general_info_and_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender_training_data_byte_vectors',
            name='course_general_info_and_about',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_byte_vectors',
            name='course_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_byte_vectors',
            name='course_objectives',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_byte_vectors',
            name='general_prerequisites',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_byte_vectors',
            name='subject_prerequisites',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='course_general_info_and_about',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='course_objectives',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='general_prerequisites',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='recommender_training_data_number_vectors',
            name='subject_prerequisites',
            field=models.CharField(max_length=5000),
        ),
    ]
