# Generated by Django 4.2.6 on 2023-10-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0012_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, unique=True),
        ),
    ]
