# Generated by Django 4.2.5 on 2024-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0013_alter_recommender_training_data_byte_vectors_course_general_info_and_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderSBERTVectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, unique=True)),
                ('description_embedding', models.CharField(max_length=10000)),
                ('objectives_embedding', models.CharField(max_length=10000)),
            ],
        ),
    ]
