# Generated by Django 4.2.6 on 2023-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0014_alter_course_prefix_alter_course_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='prefix',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
