# Generated by Django 4.2.5 on 2024-03-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0014_recommendersbertvectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='probabilitydatatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lessons_Attended', models.FloatField()),
                ('Total_lessons_in_that_period', models.FloatField()),
                ('Aggregate_points', models.FloatField()),
                ('passed', models.FloatField()),
                ('pcnt_of_lessons_attended', models.FloatField()),
                ('homework_submission_rates', models.FloatField()),
                ('activity_on_learning_platforms', models.FloatField()),
                ('CAT_1_marks', models.FloatField()),
                ('Activity_in_group_discussions', models.FloatField()),
                ('CAT_2_marks', models.FloatField()),
                ('Deadline_Adherence', models.FloatField()),
            ],
        ),
    ]
