# Generated by Django 4.2.6 on 2023-10-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0015_alter_course_name_alter_course_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_code',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
