# Generated by Django 4.2.6 on 2023-10-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0016_alter_course_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_code',
            field=models.CharField(max_length=15),
        ),
    ]
