# Generated by Django 4.2.6 on 2023-10-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0018_alter_course_name_alter_course_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
