# Generated by Django 4.2.5 on 2023-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia_app', '0004_course_data_for_recommender'),
        ('academia_app', '0022_alter_course_program_code'),
    ]

    operations = [
    ]
